#pragma once


namespace Engine
{
	typedef unsigned char					_uchar;
	typedef signed char						_char;

	typedef unsigned short					_ushort;
	typedef signed short					_short;

	typedef unsigned int					_uint;
	typedef signed int						_int;

	typedef unsigned long					_ulong;
	typedef signed long						_long;

	typedef float							_float;
	typedef double							_double;

	typedef wchar_t							_tchar;

	typedef bool							_bool;

	typedef D3DXVECTOR2						_float2;

	typedef D3DXVECTOR3						_float3;

	typedef D3DXVECTOR4						_float4;

	typedef D3DXMATRIX						_float4x4;

	enum DIRECTION { DIR_FRONT, DIR_FRONTRIGHT, DIR_RIGHT, DIR_BACKRIGHT, DIR_BACK, DIR_BACKLEFT, DIR_LEFT, DIR_FRONTLEFT, DIR_END };
	
	enum VIBuffer { VIB_RECT, VIB_CUBE, VIB_TERRAIN, VIB_OBJECT, VIB_END };


	enum OBJECT_TYPE {
		OBJECT_ROCK1, OBJECT_ROCK2, OBJECT_ROCK3,

		OBJECT_TREE_DARK1, OBJECT_TREE_DARK2, OBJECT_TREE_DARK3, OBJECT_TREE_DARK4, OBJECT_TREE_LIGHT,

		OBJECT_MATERIAL_IRON, OBJECT_MATERIAL_WOOD,

		OBJECT_PLATFORM_START, OBJECT_PLATFORM_FINISH,

		OBJECT_TRAIN_HEAD, OBJECT_TRAIN_MATERIAL, OBJECT_TRAIN_RAIL, OBJECT_TRAIN_WATER, OBJECT_TRAIN_DYNAMITE,

		OBJECT_PICKAX, OBJECT_AXE, OBJECT_BUCKET,

		OBJECT_CAMEL,

		OBJECT_RAIL_STRAIGHT, OBJECT_RAIL_CURVE,

		OBJECT_UNBREAKABLE_ROCK1, OBJECT_UNBREAKABLE_ROCK2, OBJECT_UNBREAKABLE_ROCK3,

		OBJECT_MAPCUBE,

		OBJECT_TREE_DARK_HIT1, OBJECT_TREE_DARK_HIT2, OBJECT_TREE_LIGHT_HIT1, OBJECT_TREE_LIGHT_HIT2,

		OBJECT_ROCK_HIT1, OBJECT_ROCK_HIT2,

		OBJECT_BIRD, OBJECT_BIRDLEFTWING, OBJECT_BIRDRIGHTWING, OBJECT_DYNAMITE, OBJECT_METEO, OBJECT_METEOGIANT,

		OBJECT_GIANT, OBJECT_GIANTLEFTHAND, OBJECT_GIANTRIGHTHAND, OBJECT_GIANTHEAD, OBJECT_WATER,

		OBJECT_RAIL, OBJECT_RAIL_END,

		OBJECT_END
	};
}