#pragma once

enum DIR { DIR_LEFT, DIR_RIGHT, DIR_UP, DIR_DOWN, DIR_END };

enum OBJID { BUTTON, PLAYER, MONSTER, /*BULLET, MONSTER, MOUSE, SHIELD*/OBJ_END};

enum SCENEID { SC_LOGO, SC_MENU, SC_STAGE, SC_EDIT, SC_END };

enum STATE { IDLE, WALK, ATTACK, HIT, DEAD, STATE_END };

enum GROUPID { BACKGROUND, GAMEOBJECT, EFFECT, UI, GROUP_END };

enum TEXTUREID { TEX_SINGLE, TEX_MULTI, TEX_END };
